version: '2'

services:
 postgres:
  image: postgres:latest 
  environment:
    - POSTGRES_USER=keycloak
    - POSTGRES_PASSWORD=keycloak
    - POSTGRES_DB=keycloak
  container_name: postgres
  hostname: postgres
  ports:
    - "5432:5432" 
  volumes:
    - pgsql-data:/var/lib/postgresql/data
 keycloak:  
  image: ragamiri/keycloak-postgres
  environment:
    - POSTGRES_USER=keycloak
    - POSTGRES_PASSWORD=keycloak
    - POSTGRES_DATABASE=keycloak
  container_name: keycloak
  hostname: keycloak
  links:
    - "postgres:postgres"
  ports:
    - "8080:8080"
    - "9990:9990"
    - "9999:9999"
  depends_on:
    - postgres
volumes:
  pgsql-data:
